#release configuration
#Fri Nov 15 16:04:33 IST 2024
completedPhase=end-release
exec.additionalArguments=-Dmaven.test.skip\=true
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.org.springframework.samples\:spring-petclinic=4.1.0-SNAPSHOT
project.rel.org.springframework.samples\:spring-petclinic=4.0.0
project.scm.org.springframework.samples\:spring-petclinic.connection=scm\:git\:git\://github.com/Prathushadevijsgd/spring-petclinic.git
project.scm.org.springframework.samples\:spring-petclinic.developerConnection=scm\:git\:git\://github.com/Prathushadevijsgd/spring-petclinic.git
project.scm.org.springframework.samples\:spring-petclinic.tag=HEAD
project.scm.org.springframework.samples\:spring-petclinic.url=https\://github.com/Prathushadevijsgd/spring-petclinic
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=false
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=spring-petclinic-4.0.0
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:git\://github.com/Prathushadevijsgd/spring-petclinic.git
